// src/styles/appStyles.js

export const themes = {
    light: { background: '#ffffff', text: '#121212', primary: '#e50914', secondary: '#f5f5f1', border: '#e0e0e0', header: '#121212', buttonText: '#ffffff', inputBg: '#f0f0f0', activeItem: '#e50914', activeItemText: '#ffffff', messageBgUser: '#e0e0e0', messageTextUser: '#121212', messageBgBot: '#f5f5f1', messageTextBot: '#121212' },
    dark: { background: '#121212', text: '#ffffff', primary: '#e50914', secondary: '#1c1c1c', border: '#2d2d2d', header: '#ffffff', buttonText: '#ffffff', inputBg: '#2d2d2d', activeItem: '#e50914', activeItemText: '#ffffff', messageBgUser: '#333333', messageTextUser: '#ffffff', messageBgBot: '#2d2d2d', messageTextBot: '#ffffff' },
};

export const getHomePageStyles = (theme) => ({
    pageContainer: { backgroundColor: theme.background, color: theme.text, fontFamily: "'Segoe UI', Roboto, sans-serif" },
    navbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.3rem 2rem', backgroundColor: theme.secondary, borderBottom: `1px solid ${theme.border}` },
    navLeft: { display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer' },
    logoText: { fontWeight: 'bold', fontSize: '1.5rem', color: theme.header },
    navCenter: { display: 'flex', gap: '2rem' },
    navLink: { color: theme.text, fontWeight: 500, cursor: 'pointer', background: 'none', border: 'none', padding: 0, font: 'inherit', textDecoration: 'none' },
    navRight: { display: 'flex', alignItems: 'center', gap: '1rem' },
    themeButton: { padding: '0.5rem 1rem', backgroundColor: 'transparent', color: theme.text, border: `1px solid ${theme.border}`, borderRadius: '5px', cursor: 'pointer' },
    loginButton: { padding: '0.3rem 1rem', backgroundColor: theme.primary, color: theme.buttonText, border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' },
    hero: { backgroundColor: theme.secondary, textAlign: 'center', padding: '6rem 2rem' },
    heroContent: { maxWidth: '800px', margin: '0 auto' },
    greeting: { color: theme.primary, fontSize: '2rem', margin: '0 0 0.5rem 0' },
    heroTitle: { fontSize: '3.5rem', fontWeight: 'bold', margin: '0', color: theme.header },
    heroSubtitle: { fontSize: '1.25rem', maxWidth: '600px', margin: '1rem auto 2rem auto', color: theme.text, opacity: 0.8 },
    ctaButton: { padding: '1rem 2.5rem', backgroundColor: theme.primary, color: theme.buttonText, border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold', fontSize: '1.2rem' },
    projectSection: { padding: '4rem 2rem', textAlign: 'center', backgroundColor: theme.background },
    sectionTitle: { fontSize: '2.5rem', color: theme.header, marginBottom: '1rem' },
    sectionText: { fontSize: '1.1rem', lineHeight: 1.6, maxWidth: '800px', margin: '0 auto', opacity: 0.9 },
    footer: { padding: '3rem 2rem', textAlign: 'center', backgroundColor: theme.secondary, borderTop: `1px solid ${theme.border}` },
});

export const getModalStyles = (theme) => ({
    overlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.7)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
    modal: { backgroundColor: theme.secondary, padding: '2rem', borderRadius: '8px', width: '90%', maxWidth: '400px', position: 'relative' },
    closeButton: { position: 'absolute', top: '1rem', right: '1rem', background: 'none', border: 'none', cursor: 'pointer' },
    title: { textAlign: 'center', margin: '0 0 1.5rem 0', color: theme.header },
    form: { display: 'flex', flexDirection: 'column', gap: '1rem' },
    input: { padding: '0.75rem', borderRadius: '5px', border: `1px solid ${theme.border}`, backgroundColor: theme.inputBg, color: theme.text },
    submitButton: { padding: '0.75rem', backgroundColor: theme.primary, color: theme.buttonText, border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' },
    toggleText: { textAlign: 'center', marginTop: '1rem', fontSize: '0.9rem' },
    toggleLink: { color: theme.primary, cursor: 'pointer', fontWeight: 'bold' },
});

export const getPdfChatStyles = (theme) => ({
    appContainer: { display: 'flex', height: 'calc(100vh - 49px)', backgroundColor: theme.background, color: theme.text, fontFamily: "'Segoe UI', Roboto, sans-serif" },
    historySidebar: { width: '280px', backgroundColor: theme.secondary, padding: '1rem', borderRight: `1px solid ${theme.border}`, display: 'flex', flexDirection: 'column' },
    historyHeader: { display: 'flex', alignItems: 'center', gap: '0.5rem', color: theme.header, paddingBottom: '1rem', borderBottom: `1px solid ${theme.border}` },
    historyTitle: { margin: 0, fontSize: '1.2rem' },
    newChatButton: { width: '100%', padding: '0.5rem', margin: '1rem 0', backgroundColor: theme.primary, color: theme.buttonText, border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold', fontSize: '0.9rem' },
    sessionList: { flexGrow: 1, overflowY: 'auto' },
    sessionItem: { padding: '0.75rem', borderRadius: '5px', marginBottom: '0.5rem', cursor: 'pointer', border: `1px solid ${theme.border}` },
    activeSessionItem: { backgroundColor: theme.primary, color: theme.activeItemText, borderColor: theme.primary },
    sessionPersona: { margin: '0 0 0.25rem 0', fontWeight: 'bold', fontSize: '0.9rem' },
    sessionJob: { margin: 0, opacity: 0.8, fontSize: '0.85rem' },
    sessionTimestamp: { margin: '0.5rem 0 0 0', fontSize: '0.75rem', opacity: 0.6 },
    mainContent: { display: 'flex', flexGrow: 1, overflow: 'hidden' },
    viewerPanel: { flex: 0.6, display: 'flex', flexDirection: 'column', backgroundColor: theme.background, position: 'relative', borderRight: `1px solid ${theme.border}` },
    viewerPlaceholder: { flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '1rem', textAlign: 'center', color: theme.text, opacity: 0.7 },
    chatPanel: { flex: 1, backgroundColor: theme.secondary, padding: '1rem', display: 'flex', flexDirection: 'column', overflowY: 'hidden' },
    sidebarTitle: { margin: '0 0 1rem 0', color: theme.header, borderBottom: `1px solid ${theme.border}`, paddingBottom: '0.5rem' },
    chatControls: { display: 'flex', flexDirection: 'column', gap: '0.5rem' },
    uploadButton: { padding: '0.75rem', backgroundColor: theme.primary, color: theme.buttonText, border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold', textAlign: 'center' },
    pdfList: { display: 'flex', gap: '0.5rem', overflowX: 'auto', padding: '0.5rem 0' },
    pdfListItem: { padding: '0.4rem 0.8rem', borderRadius: '5px', cursor: 'pointer', whiteSpace: 'nowrap', border: `1px solid ${theme.border}`, backgroundColor: 'transparent', color: theme.text },
    activePdfListItem: { backgroundColor: theme.activeItem, color: theme.activeItemText, fontWeight: 'bold', borderColor: theme.primary },
    input: { flex: 1, padding: '0.3rem 0.6rem', fontSize: '0.9rem', borderRadius: '5px', border: `1px solid ${theme.border}`, backgroundColor: theme.inputBg, color: theme.text, width: 'calc(100% - 1.5rem)' },
    textarea: { minHeight: '60px', resize: 'vertical', fontFamily: "'Segoe UI', Roboto, sans-serif", padding: '0.3rem 0.6rem', fontSize: "0.9rem" },
    button: { padding: '0.4rem 0.9rem', backgroundColor: theme.primary, color: theme.buttonText, border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold', width: '100%' },
    loadingIndicator: { alignSelf: 'center', color: theme.text, opacity: 0.8, fontStyle: 'italic', padding: '1rem' },
    placeholderText: { textAlign: 'center', opacity: 0.7, margin: 'auto' },
    analysisResult: { padding: '0.5rem', backgroundColor: theme.background, borderRadius: '8px', marginBottom: '1rem', fontSize: '1.1rem' },
    analysisSnippet: { borderLeft: `3px solid ${theme.primary}`, padding: '10px', margin: '10px 0', backgroundColor: theme.inputBg, borderRadius: '4px', cursor: 'pointer', opacity: 0, animation: 'fadeIn 0.5s forwards', fontSize: '0.9rem', textAlign: "justify" },
    analysisReason: { fontStyle: 'italic', opacity: 0.9, marginBottom: '8px', fontSize: '0.9rem', textAlign: "justify" },
    sectionTitleText: { fontWeight: 'bold', margin: '0 0 8px 0', fontSize: '0.9rem', textAlign: "justify" },
    snippetFooter: { textAlign: 'right', opacity: 0.7, marginTop: '8px', fontSize: '0.9rem' },
    llmInsightsContainer: { marginTop: '0.7rem', padding: '1rem', backgroundColor: theme.secondary, borderRadius: '8px', border: `1px solid ${theme.border}` },
    insightsHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.7rem', fontSize: '1.1rem', fontWeight: 'bold', marginTop: '0.5rem' },
    translateAllContainer: { display: 'flex', alignItems: 'center' },
    insightCategory: { marginBottom: '0.5rem', fontSize: '0.9rem', textAlign: "justify" },
    insightCategoryTitle: { margin: '0 0 0.5rem 0', color: theme.header, fontWeight: 'bold', fontSize: '0.9rem', textAlign: "justify" },
    podcastContainer: { marginTop: '0.5rem', padding: '1rem', backgroundColor: theme.secondary, borderRadius: '8px', border: `1px solid ${theme.border}` },
    podcastControls: { display: 'flex', gap: '0.5rem', alignItems: 'center' },
    languageSelector: { padding: '0.75rem', backgroundColor: theme.inputBg, color: theme.text, border: `1px solid ${theme.border}`, borderRadius: '5px' },
    audioPlayer: { width: '100%', marginTop: '1rem' },
    showOriginalButton: { background: 'none', border: `1px solid ${theme.border}`, color: theme.text, cursor: 'pointer', borderRadius: '4px', padding: '2px 6px', fontSize: '0.75rem', marginRight: '8px' },
    tabsContainer: { display: 'flex', borderBottom: `1px solid ${theme.border}`, flexShrink: 0 },
    tabButton: {
        padding: '0.75rem 1.5rem',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        color: theme.text,
        opacity: 0.7,
        borderBottom: '3px solid transparent'
    },
    activeTab: {
        opacity: 1,
        borderBottom: `3px solid ${theme.primary}`,
        fontWeight: 'bold'
    },
    insightsPanel: {
        flex: 1,
        overflowY: 'auto',
        padding: '0.5rem',
    },
    selectionInsightsContainer: {
        padding: '0.5rem',
        backgroundColor: theme.background,
        borderRadius: '8px',
        animation: 'fadeIn 0.5s forwards'
    },
});